version: '3.1'

services:
  comparator-node-dev:
    container_name: comparator-node-dev
    build:
      context: ./server
    ports:
      - 8080:8080
    volumes:
      - .:/appBack
      - /appBack/node_modules
    command: ["nodemon", "server"]
    env_file:
      - ./.env-dev
    depends_on:
      - mariadb

  comparator-angular-dev:
    container_name: comparator-angular-dev
    build:
      context: ./client
    ports:
      - 4200:4200
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    env_file:
      - ./.env-dev
    depends_on:
      - comparator-node-dev
  
  comparator-adminer-dev:
    container_name: comparator-adminer-dev
    image: adminer
    depends_on:
      - comparator-mariadb-dev
    ports:
      - "86:8080"
  
  comparator-mariadb-dev:
    container_name: comparator-mariadb-dev
    image: mysql
    build: 
      context: ./BDD
    volumes:
      - ./BDD/data:/var/lib/mysql:z
    env_file:
      - ./.env-dev
    ports:
      - 3306:3306
