version: '3.1'

services:
  comparator-node:
    container_name: comparator-node
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "prod"]
    env_file:
      - ./.env-prod
    
