version: '3.1'

services:
  comparator-node-prod:
    container_name: comparator-node-prod
    build:
      context: ./server
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "prod"]
    env_file:
      - ./.env-prod
    
  comparator-mariadb-dev:
    container_name: comparator-mariadb-dev
    image: mysql
    build: 
      context: ./BDD
    volumes:
      - ./BDD/data:/var/lib/mysql:z
    env_file:
      - ./.env-prod
    ports:
      - 3306:3306
